apiVersion: v1
kind: ReplicationController
metadata:
    name: yesodweb
    labels:
        app: yesodweb
spec:
  replicas: 1
  template:
    metadata:
        labels:
            app: yesodweb
    spec:
        containers:
        - name: yesodweb
          resources:
            limits:
              memory: 800Mi
          image: snoyberg/yesodweb:latest
          command: ["yesodweb", "development"]
          workingDir: /app
          ports:
          - containerPort: 3001
            hostPort: 3001
          env:
          - name: PORT
            value: "3001"
          livenessProbe:
              httpGet:
                  path: /
                  port: 3001
